version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cligo
  - davecgh
  - eteran
  - go-difflib
  - go-spew
  - gopkg
  - pmezard
  - Positionals
  - stretchr
ignoreWords: []
import: []
